/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sessionsapp_player_SSP */

#ifndef _Included_org_sessionsapp_player_SSP
#define _Included_org_sessionsapp_player_SSP
#ifdef __cplusplus
extern "C" {
#endif
#undef org_sessionsapp_player_SSP_SSP_OK
#define org_sessionsapp_player_SSP_SSP_OK 0L
#undef org_sessionsapp_player_SSP_SSP_ERROR_UNKNOWN
#define org_sessionsapp_player_SSP_SSP_ERROR_UNKNOWN 1L
/*
 * Class:     org_sessionsapp_player_SSP
 * Method:    SSP_GetVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_sessionsapp_player_SSP_SSP_1GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_sessionsapp_player_SSP
 * Method:    SSP_Init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_sessionsapp_player_SSP_SSP_1Init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_sessionsapp_player_SSP
 * Method:    SSP_InitDevice
 * Signature: (IIIIZ)I
 */
JNIEXPORT jint JNICALL Java_org_sessionsapp_player_SSP_SSP_1InitDevice
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean);

/*
 * Class:     org_sessionsapp_player_SSP
 * Method:    SSP_FreeDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_sessionsapp_player_SSP_SSP_1FreeDevice
  (JNIEnv *, jclass);

/*
 * Class:     org_sessionsapp_player_SSP
 * Method:    SSP_Free
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_sessionsapp_player_SSP_SSP_1Free
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
